name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.4

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out vger 
        uses: actions/checkout@v2
      - name: Build vger 
        run: |
          set -euo pipefail
          xcodebuild -scheme vger clean build | xcpretty

  demo:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out vger-demo
        uses: actions/checkout@v2
      - name: Build vger-demo
        run: |
          set -euo pipefail
          cd Demo
          xcodebuild -scheme "VgerDemo (macOS)" clean build | xcpretty