name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.4

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out vger 
        uses: actions/checkout@v2
      - name: Build vger 
        run: |
          set -euo pipefail
          xcodebuild -scheme vger -destination 'platform=OS X,arch=x86_64' clean build | xcpretty

  demo:
    runs-on: macos-latest
    steps:
      - name: Check out vger-demo
        uses: actions/checkout@v2
      - name: Build vger-demo
        run: |
          set -euo pipefail
          cd Demo
          xcodebuild -scheme "VgerDemo (macOS)" -destination 'platform=OS X,arch=x86_64' clean build | xcpretty
