name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.5

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['12.5']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out vger 
        uses: actions/checkout@v2
      - name: Build vger 
        run: |
          set -euo pipefail
          xcodebuild -scheme vger clean build | xcpretty
